table usuario {
  id_usuario int [pk, increment]
  nombre varchar(255)
  edad int
  trabajo varchar(255)
  cuenta_bancaria varchar(255)
}

table ingreso {
  id_ingreso int [pk, increment]
  id_usuario int [ref: > usuario.id_usuario]
  fecha date
  abono float
  gasto float
}

table chat {
  id_chat int [pk, increment]
  id_usuario int [ref: > usuario.id_usuario]
}

table mensaje {
  id_mensaje int [pk, increment]
  id_chat int [ref: > chat.id_chat]
  contenido text
}

table ui {
    id_ui int [pk, increment]
    ui_json json
    }

table vector_intencion {
  edad int
  trabajo varchar(255)
  ingreso_mensual float
  gasto_mensual float
  intencion varchar(255)
}

table documentos {
  id_documento int [pk, increment]
  nombre varchar(255)
  contenido text
}

